---
title: "Teaching"
include-in-header:
      - text: |
          <meta name='description' content='The teaching history of John Reaves, PhD student in economics at Michigan State University (MSU). This includes a graduate course, PPL 802, and the IIT fellowship at James Madison College.'>
---

I have served as a teaching assistant during most of my time at Michigan State, and had the privilege to teach courses twice---once online, and once in person.

## Instructor

* PPL 802 — Quantitative Methods in Public Policy II,  Spring 2024
* EC 201 — Introduction to Microeconomics, Summer 2023 (Online)

## Teaching Assistant

* EC 201 — Introduction to Microeconomics, Fall 2022-Fall 2023, Fall 2024
* EC 301 — Intermediate Microeconomics, Spring 2022
* EC 302 — Intermediate Macroeconomics, Fall 2021

## Selected student feedback

* "He always took the time to explain things in ways we could explain and never had a[n] issue to help [one] on [one]."
* "[The instructor] answered questions quickly and effectively." 
<br><br>
* PPL 802: 
    * Course was well organized (100% agree)
    * Created a supportive atmosphere for learning (77.8% agree)
* EC 201: 
    * Course was well organized (91.4% agree)
    * Created a supportive atmosphere for learning (88.6% agree)

## Other

I participated in the IIT Fellowship, a teaching fellowship organized by James 
Madison College at MSU. 

I was also fortunate enough to be sponsored by MSU to give a boot camp in R, 
aimed at economics graduate students. You can find the materials for the boot 
camp in the following places:

* [Session 1](https://mediaspace.msu.edu/media/t/1_biq5kvtp)
* [Session 2](https://mediaspace.msu.edu/media/t/1_ljw6r4xw)
* [Reference document](r-workshop.html)
* [Zillow dataset](https://drive.google.com/file/d/1klJ7qO-W2wgRhv-5oZkgq2JeCcuAwgTI/view?usp=sharing)
